Implement LIC 12
sofrel-group14/decide pull request #58
Opened 2021-02-02 20:04 UTC by K2017

Fixes #9

2021-02-02 22:00 UTC, andreaskth requested changes
Apart from lacking comments describing tests it seems to be "all good" as far as I can see. Good job!

2021-02-02 22:00 UTC, andreaskth commented on src/test/java/LIC12Test.java
> +    var points = new Point[] {
This test needs a comment in natural language describing it

2021-02-02 22:00 UTC, andreaskth commented on src/test/java/LIC12Test.java
> +    var points = new Point[] {
This one also needs descriptive comment

2021-02-03 08:25 UTC, elmaxe approved these changes
Needs comments on the tests

2021-02-03 08:35 UTC, elmaxe approved these changes

2021-02-03 09:07 UTC, andreaskth approved these changes
Looks good now!

2021-02-03 09:07 UTC, merged